# Generated by Django 4.1 on 2022-09-04 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MortgageOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=255, verbose_name='Название банка')),
                ('term_min', models.PositiveIntegerField(verbose_name='Срок ипотеки, ОТ')),
                ('term_max', models.PositiveIntegerField(verbose_name='Срок ипотеки, ДО')),
                ('rate_min', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='Ставка, ОТ')),
                ('rate_max', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='Ставка, ДО')),
                ('payment_min', models.PositiveIntegerField(verbose_name='Сумма кредита, ОТ')),
                ('payment_max', models.PositiveIntegerField(verbose_name='Сумма кредита, ДО')),
            ],
            options={
                'verbose_name': 'Кредитное предложение',
                'verbose_name_plural': 'Кредитные предложения',
            },
        ),
    ]
